services:
  catalog-service:
    build: .
    container_name: catalog-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongo_catalog:27017/catalog
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key.pem
    secrets:
      - jwt_public_key.pem
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo_catalog
    ports:
      - "27018:27017"
    volumes:
      - mongo_catalog_data:/data/db
    restart: unless-stopped

secrets:
  jwt_public_key.pem:
    file: ./public_key.pem

volumes:
  mongo_catalog_data:
