version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo:27017/inventory
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key.pem
    secrets:
      - jwt_public_key.pem
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

secrets:
  jwt_public_key.pem:
    file: ./public_key.pem

volumes:
  mongo_data:
